export const ACTIVE_PROCESS_TYPE = {
	CREATED: 1,
	COMPLETED: 2,
	NOT_CREATED: 3,
};

export const TEMPLATE_ACTION = {
	POSITIVE_TYPE: 1,
	NEGATIVE_TYPE: 2,
	MAKE_COMMENT_AND_NOTIFY_EXECUTOR: 3,
	SKIP: 5,
	MAKE_COMMENT_AND_NOTIFY_EXECUTOR_DOCUMENT: 7,
	ATTRACT: 6,
	CUSTOM: 10,
	POST_COMMENT: 11,
};

export const PROCESS_STATUS = {
	PREPARATION: 1,
	DONE: 2,
};

export const GROUP_TYPE = {
	SERIAL_TYPE: 1,
	PARALLEL_TYPE: 2,
	ONE_OF_TYPE: 3,
};

export const GROUP_TYPE_FILL = {	
	ANY_TYPE: 1,
	FROM_LIST_TYPE: 2,
};

export const GROUP_STATUS = {
	DEACTIVATED: 1,
	ACTIVE: 2,
	DECIDED: 3,
};

export const PARTICIPANT_TYPE = {
	EXECUTOR: 1,
	DOCUMENT_EXECUTOR: 4,
	PARTICIPANT: 2,
	EMPLOYEE: 3,
};

export const PARTICIPANT_STATUS = {
	WAIT: 1,
	ACTIVE: 2,
	DECIDED: 3,
};