export const ACTIVE_PROCESS_TYPE = {
	CREATED: 1,
	COMPLETED: 2,
	NOT_CREATED: 3,
};

export const TEMPLATE_ACTION = {
	POSITIVE_ACTION: 1,
	NEGATIVE_ACTION: 2,
	MAKE_COMMENT_AND_NOTIFY_PROCESS_EXECUTOR: 3,
	REPLY_COMMENT: 4,
	SKIP_ACTION: 5,
	ATTRACT_ACTION: 6,
	MAKE_COMMENT_AND_NOTIFY_DOCUMENT_EXECUTOR: 7,
	REPLY_COMMENT_DOCUMENT_EXECUTOR: 8,
	SKIPPED_ACTION: 9,
	MAKE_COMMENT_AND_NOTIFY_PARTICIPANTS: 10,
	POST_COMMENT_ACTION: 11,
	REPLY_COMMENT_PARTICIPANT: 12,
	REQUEST_CHANGE_DEADLINE: 13,
	CONFIRM_DEADLINE_CHANGE: 14,
	CANCEL_DEADLINE_CHANGE: 15,
	REQUEST_CANCELLATION: 16,
	CONFIRM_CANCELLATION: 17,
	CANCEL_CANCELLATION: 18,
	REQUEST_EXECUTOR_CHANGE: 19,
	CONFIRM_EXECUTOR_CHANGE: 20,
	CANCEL_EXECUTOR_CHANGE: 21,
	REPLY_COMMENT_ANTOTHER_EMPLOYEE: 22,
	MAKE_COMMENT_AND_NOTIFY_ANOTHER_EMPLOYEE: 23
};

export const PROCESS_STATUS = {
	PREPARATION: 1,
	DONE: 2,
};

export const GROUP_TYPE = {
	SERIAL_TYPE: 1,
	PARALLEL_TYPE: 2,
	ONE_OF_TYPE: 3,
};

export const GROUP_TYPE_FILL = {
	ANY_TYPE: 1,
	FROM_LIST_TYPE: 2,
};

export const GROUP_STATUS = {
	DEACTIVATED: 1,
	ACTIVE: 2,
	DECIDED: 3,
};

export const PARTICIPANT_TYPE = {
	EXECUTOR: 1,
	DOCUMENT_EXECUTOR: 4,
	PARTICIPANT: 2,
	EMPLOYEE: 3,
};

export const PARTICIPANT_STATUS = {
	WAIT: 1,
	ACTIVE: 2,
	DECIDED: 3,
};