export const DOCUMENT_lIST_KEY = Symbol('DOCUMENT_lIST_KEY');
export const NEED_ACTION_lIST_KEY = Symbol('NEED_ACTION_lIST_KEY');
export const SELECT_ROUTE_ELEMENT_KEY = Symbol('SELECT_ROUTE_ELEMENT_KEY');



