export const DOCUMENT_lIST_KEY = Symbol('DOCUMENT_lIST_KEY');
export const NEED_ACTION_lIST_KEY = Symbol('NEED_ACTION_lIST_KEY');
export const SELECT_ROUTE_ELEMENT_KEY = Symbol('SELECT_ROUTE_ELEMENT_KEY');
export const NEED_ACTION_SUBUSER_LIST_KEY = Symbol('NEED_ACTION_SUBUSER_LIST_KEY');
export const TEMPLATE_REQUIREMENTS = Symbol('TEMPLATE_REQUIREMENTS');